import React from 'react';
import './PhotoMask.css'
const Temp1 = () => {
    const style={
        color:'#fff'
    }
    return (
        <div className='temp'style={style}>
            <div>
                <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit.</h1>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat aut ipsum, nesciunt omnis aliquam pariatur! Harum animi architecto maiores sit veniam, cupiditate obcaecati porro voluptas, corporis quos ut quasi possimus sapiente incidunt esse? Fugiat, distinctio ut! Dolore quasi aliquid quia eaque laboriosam sapiente quam aut unde, fugit culpa quod enim dolorum delectus? Eveniet nulla voluptates quo modi placeat ipsa perspiciatis officiis possimus consequatur hic esse fuga iusto consectetur, accusamus rem explicabo dignissimos iure dicta id nostrum ullam. Quas vitae modi nesciunt. Molestias perspiciatis error alias, velit facere tempora atque numquam esse repellat ullam deserunt impedit, maxime culpa totam similique? Officiis enim mollitia sed omnis fuga voluptatibus quasi doloribus cupiditate facilis saepe. Delectus, accusamus placeat! Quidem, illum? Consequatur dignissimos cum vero eaque quidem, excepturi labore dolore alias, neque perferendis eligendi nam quibusdam suscipit iste? Rem impedit modi perspiciatis minima similique nisi quia nemo ratione expedita. Maxime quisquam non laborum fugit aperiam quia qui in id corrupti adipisci, officia modi voluptatum aspernatur tenetur? Quo excepturi possimus a reprehenderit consequatur aperiam quae quis, optio, voluptatibus minus quaerat laudantium fugit pariatur alias, inventore accusamus! Nulla rerum libero neque enim cupiditate voluptate officia laudantium quod labore suscipit delectus repellendus reiciendis ratione quidem, officiis maxime, eius nostrum nam! Nihil, illum? Eum rem, necessitatibus perferendis non unde ab veniam doloribus fugit alias laborum pariatur, dolorum quisquam laboriosam expedita beatae tenetur, velit nobis! Autem fugiat repudiandae quidem iusto repellendus quaerat eos distinctio eaque perferendis ullam, facere natus omnis iure ex sit, at debitis ipsam in blanditiis suscipit. Repudiandae voluptates laboriosam earum sunt in, saepe vero magnam accusantium similique facilis quis nesciunt odit quo mollitia asperiores nisi soluta hic eius quia corrupti voluptas eaque necessitatibus, dignissimos velit? Ipsa nesciunt deleniti eos soluta voluptate, quibusdam fugiat amet incidunt quos, repellendus consequatur quisquam commodi nihil est ullam aut eveniet. Libero, fugiat.</p>
            </div>
            <div>
                <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit.</h1>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat aut ipsum, nesciunt omnis aliquam pariatur! Harum animi architecto maiores sit veniam, cupiditate obcaecati porro voluptas, corporis quos ut quasi possimus sapiente incidunt esse? Fugiat, distinctio ut! Dolore quasi aliquid quia eaque laboriosam sapiente quam aut unde, fugit culpa quod enim dolorum delectus? Eveniet nulla voluptates quo modi placeat ipsa perspiciatis officiis possimus consequatur hic esse fuga iusto consectetur, accusamus rem explicabo dignissimos iure dicta id nostrum ullam. Quas vitae modi nesciunt. Molestias perspiciatis error alias, velit facere tempora atque numquam esse repellat ullam deserunt impedit, maxime culpa totam similique? Officiis enim mollitia sed omnis fuga voluptatibus quasi doloribus cupiditate facilis saepe. Delectus, accusamus placeat! Quidem, illum? Consequatur dignissimos cum vero eaque quidem, excepturi labore dolore alias, neque perferendis eligendi nam quibusdam suscipit iste? Rem impedit modi perspiciatis minima similique nisi quia nemo ratione expedita. Maxime quisquam non laborum fugit aperiam quia qui in id corrupti adipisci, officia modi voluptatum aspernatur tenetur? Quo excepturi possimus a reprehenderit consequatur aperiam quae quis, optio, voluptatibus minus quaerat laudantium fugit pariatur alias, inventore accusamus! Nulla rerum libero neque enim cupiditate voluptate officia laudantium quod labore suscipit delectus repellendus reiciendis ratione quidem, officiis maxime, eius nostrum nam! Nihil, illum? Eum rem, necessitatibus perferendis non unde ab veniam doloribus fugit alias laborum pariatur, dolorum quisquam laboriosam expedita beatae tenetur, velit nobis! Autem fugiat repudiandae quidem iusto repellendus quaerat eos distinctio eaque perferendis ullam, facere natus omnis iure ex sit, at debitis ipsam in blanditiis suscipit. Repudiandae voluptates laboriosam earum sunt in, saepe vero magnam accusantium similique facilis quis nesciunt odit quo mollitia asperiores nisi soluta hic eius quia corrupti voluptas eaque necessitatibus, dignissimos velit? Ipsa nesciunt deleniti eos soluta voluptate, quibusdam fugiat amet incidunt quos, repellendus consequatur quisquam commodi nihil est ullam aut eveniet. Libero, fugiat.</p>
            </div>
            <div>
                <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit.</h1>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat aut ipsum, nesciunt omnis aliquam pariatur! Harum animi architecto maiores sit veniam, cupiditate obcaecati porro voluptas, corporis quos ut quasi possimus sapiente incidunt esse? Fugiat, distinctio ut! Dolore quasi aliquid quia eaque laboriosam sapiente quam aut unde, fugit culpa quod enim dolorum delectus? Eveniet nulla voluptates quo modi placeat ipsa perspiciatis officiis possimus consequatur hic esse fuga iusto consectetur, accusamus rem explicabo dignissimos iure dicta id nostrum ullam. Quas vitae modi nesciunt. Molestias perspiciatis error alias, velit facere tempora atque numquam esse repellat ullam deserunt impedit, maxime culpa totam similique? Officiis enim mollitia sed omnis fuga voluptatibus quasi doloribus cupiditate facilis saepe. Delectus, accusamus placeat! Quidem, illum? Consequatur dignissimos cum vero eaque quidem, excepturi labore dolore alias, neque perferendis eligendi nam quibusdam suscipit iste? Rem impedit modi perspiciatis minima similique nisi quia nemo ratione expedita. Maxime quisquam non laborum fugit aperiam quia qui in id corrupti adipisci, officia modi voluptatum aspernatur tenetur? Quo excepturi possimus a reprehenderit consequatur aperiam quae quis, optio, voluptatibus minus quaerat laudantium fugit pariatur alias, inventore accusamus! Nulla rerum libero neque enim cupiditate voluptate officia laudantium quod labore suscipit delectus repellendus reiciendis ratione quidem, officiis maxime, eius nostrum nam! Nihil, illum? Eum rem, necessitatibus perferendis non unde ab veniam doloribus fugit alias laborum pariatur, dolorum quisquam laboriosam expedita beatae tenetur, velit nobis! Autem fugiat repudiandae quidem iusto repellendus quaerat eos distinctio eaque perferendis ullam, facere natus omnis iure ex sit, at debitis ipsam in blanditiis suscipit. Repudiandae voluptates laboriosam earum sunt in, saepe vero magnam accusantium similique facilis quis nesciunt odit quo mollitia asperiores nisi soluta hic eius quia corrupti voluptas eaque necessitatibus, dignissimos velit? Ipsa nesciunt deleniti eos soluta voluptate, quibusdam fugiat amet incidunt quos, repellendus consequatur quisquam commodi nihil est ullam aut eveniet. Libero, fugiat.</p>
            </div>
            <div>
                <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit.</h1>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat aut ipsum, nesciunt omnis aliquam pariatur! Harum animi architecto maiores sit veniam, cupiditate obcaecati porro voluptas, corporis quos ut quasi possimus sapiente incidunt esse? Fugiat, distinctio ut! Dolore quasi aliquid quia eaque laboriosam sapiente quam aut unde, fugit culpa quod enim dolorum delectus? Eveniet nulla voluptates quo modi placeat ipsa perspiciatis officiis possimus consequatur hic esse fuga iusto consectetur, accusamus rem explicabo dignissimos iure dicta id nostrum ullam. Quas vitae modi nesciunt. Molestias perspiciatis error alias, velit facere tempora atque numquam esse repellat ullam deserunt impedit, maxime culpa totam similique? Officiis enim mollitia sed omnis fuga voluptatibus quasi doloribus cupiditate facilis saepe. Delectus, accusamus placeat! Quidem, illum? Consequatur dignissimos cum vero eaque quidem, excepturi labore dolore alias, neque perferendis eligendi nam quibusdam suscipit iste? Rem impedit modi perspiciatis minima similique nisi quia nemo ratione expedita. Maxime quisquam non laborum fugit aperiam quia qui in id corrupti adipisci, officia modi voluptatum aspernatur tenetur? Quo excepturi possimus a reprehenderit consequatur aperiam quae quis, optio, voluptatibus minus quaerat laudantium fugit pariatur alias, inventore accusamus! Nulla rerum libero neque enim cupiditate voluptate officia laudantium quod labore suscipit delectus repellendus reiciendis ratione quidem, officiis maxime, eius nostrum nam! Nihil, illum? Eum rem, necessitatibus perferendis non unde ab veniam doloribus fugit alias laborum pariatur, dolorum quisquam laboriosam expedita beatae tenetur, velit nobis! Autem fugiat repudiandae quidem iusto repellendus quaerat eos distinctio eaque perferendis ullam, facere natus omnis iure ex sit, at debitis ipsam in blanditiis suscipit. Repudiandae voluptates laboriosam earum sunt in, saepe vero magnam accusantium similique facilis quis nesciunt odit quo mollitia asperiores nisi soluta hic eius quia corrupti voluptas eaque necessitatibus, dignissimos velit? Ipsa nesciunt deleniti eos soluta voluptate, quibusdam fugiat amet incidunt quos, repellendus consequatur quisquam commodi nihil est ullam aut eveniet. Libero, fugiat.</p>
            </div>
        </div>
    );
};

export default Temp1;